all:
	$ gcc battle.c -o battle
	$ gcc player.c -o player
clean:
	rm battle -f
	rm player -f
	rm log_battleA.txt -f
	rm log_battleB.txt -f
	rm log_battleC.txt -f
	rm log_battleD.txt -f
	rm log_battleE.txt -f
	rm log_battleF.txt -f
	rm log_battleG.txt -f
	rm log_battleH.txt -f
	rm log_battleI.txt -f
	rm log_battleJ.txt -f
	rm log_battleK.txt -f
	rm log_battleL.txt -f
	rm log_battleM.txt -f
	rm log_battleN.txt -f
	rm log_player0.txt -f
	rm log_player1.txt -f
	rm log_player2.txt -f
	rm log_player3.txt -f
	rm log_player4.txt -f
	rm log_player5.txt -f
	rm log_player6.txt -f
	rm log_player7.txt -f
	rm *.fifo -f